server:
  port: 9009
spring:
  application:
    name: zipkin-server-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://192.168.158.132:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1