server:
  port: 9006
spring:
  application:
    name: gateway-zuul-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    route-demo:
      service-Id: rest-demo
      path: /rest/**
  PreRequestLogFilter:
    pre:
      disable: true

