spring:
  application:
    name: Consumer-Hystrix-Demo
server:
  port: 9005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true