spring:
  application:
    name: Rest-Demo
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: false #是否以ip地址形式注册服务，默认为false，为false时则以hostname作为地址