spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1
  application:
    name: Consumer-Demo
server:
  port: 9004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
Rest-Demo:
  ribbon:
    NFLoadBalancerRuleClassName: com.xdlysk.consumerdemo.MyLoadBalanceRule
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
